### ISSUE TITLE
Should be client sided

### ISSUE THREAD

**Issue by Poopooracoocoo** [txnimc/SodiumDynamicLights#18]
It's being loaded on servers

https://github.com/txnimc/SodiumDynamicLights/blob/main/src/main/resources/fabric.mod.json#L17

**Comment by txnitxnichopper** [comment]
should be fixed in latest release

**Comment by Poopooracoocoo** [comment]
I just had a look at https://github.com/txnimc/SodiumDynamicLights/blob/main/src/main/resources/fabric.mod.json#L17 and it's still not client sided.
