### ISSUE TITLE
[BUG] Crash on start-up caused by Spell Engine and Simply Swords [Fabric 1.20.1/0.16.5]

### ISSUE THREAD

**Issue by pokesmells** [txnimc/SodiumDynamicLights#9]
When loading the game, it crashes on startup
https://mclo.gs/Hh0lrgR

**Comment by pokesmells** [comment]
> When loading the game, it crashes on startup https://mclo.gs/Hh0lrgR

https://mclo.gs/0N0B1Jv - latest.log

**Comment by memphismc** [comment]
same

[crash-2024-09-14_21.13.57-client.txt](https://github.com/user-attachments/files/17003404/crash-2024-09-14_21.13.57-client.txt)

**Comment by nthxny** [comment]
I've renamed the entrypoint back to the lambdynlights namespace, so this should be resolved. Tested and working with Spell Engine and other mods using the API

**Comment by memphismc** [comment]
[crash-2024-09-22_20.40.28-client.txt](https://github.com/user-attachments/files/17090639/crash-2024-09-22_20.40.28-client.txt)

still crashes on startup, using latest version

**Comment by pokesmells** [comment]
> I've renamed the entrypoint back to the lambdynlights namespace, so this should be resolved. Tested and working with Spell Engine and other mods using the API

Still Crashes on start-up

https://mclo.gs/D3lJnsk

**Comment by txnitxnichopper** [comment]
It seems I had only tested on Fabric 1.21, which doesn't even have the original LambDynLights yet. So nothing was happening and nothing was crashing lol. Should be properly fixed now in latest update

**Comment by memphismc** [comment]
yeah its fixed 👍
